### PR TITLE
remove quote in validation

### LINKED ISSUE #18: A valid table name is considered invalid due to the table name validation
Test 1:
```
sourceTable: xxx1xxx-yy-zzzzz

source.tableName must follow AWS naming rules (3-255 length, and only the following characters: a-z, A-Z, 0-9, _-.)
{ count: 0, status: 'FAIL' }
```

Test 2:
```
sourceTable: xxx1abc-yy-123
source.tableName must follow AWS naming rules (3-255 length, and only the following characters: a-z, A-Z, 0-9, _-.)
{ count: 0, status: 'FAIL' }
```

### PR DESCRIPTION
**Pull request by siutsin**
fix #18

### CODE REVIEW

File: validate.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ var ConfigError = require('./error')
 var regex = new RegExp('^[a-zA-Z0-9_.-]{3,255}$');
 
 var validate = function (options, field) {
-  if (!regex.test(options['field'] || '')) {
+  if (!regex.test(options[field] || '')) {
```
Comment (najimou) [inline validate.js]: not enough need to replace below by:
module.exports.config = function (options) {
    return validate(options.source, 'tableName') && validate(options.destination, 'tableName') // check both source and destination
}

Comment (siutsin) [reply validate.js]: @najimou thanks, check `.tableName` now.

**Comment by tszebeni** [comment]
Tried this tool recenty, run into the same issue, could patch manually. Just a recommendation here: write unit tests and use branching strategy to release only a version which passes the tests
